### PR TITLE
changes to date

### PR DESCRIPTION
**Pull request by tomByrer**
changes to date

### CODE REVIEW

**Comment by jonom** [comment]
Thanks Tom, these changes all make sense. Do you want me to merge these soon or do you want to keep working on stuff? I know I said I prefer a single commit per issue *but* I don't want to merge any revert commits - so I'd be happy for you to squash all of this in to one commit if you like, call it something like 'Optimisations' and just summarise each of the things you did in the message.

**Comment by jonom** [comment]
Or rather, squash the last 4 in to one. May as well leave the image one separate. Or whatever :D

**Comment by tomByrer** [comment]
> Or rather, squash the last 4 in to one. May as well leave the image one separate. Or whatever :D

Sounds like best bet.  Might be day or 3.

**Comment by tomByrer** [comment]
Seems removing the `data` object was only a slight improvement, likely as much as [removing 3/4 of the elements lookups](https://github.com/tomByrer/jquery-focuspoint/commit/6a2907bde0d4c720eadc4198ca1fc865df72753d#diff-f0cf615690c9b6135dba15b53228f01fL219).
Likely modern JS engines automatically do optimizations like [this](https://github.com/tomByrer/jquery-focuspoint/commit/7872c940ef67a9b53dac1ff6462b3a6f2be4eed5#diff-f0cf615690c9b6135dba15b53228f01fR2200, but I put in code anyhow; less horizontal noise when eyeballing.

**Comment by jonom** [comment]
Thanks for your efforts Tom. If there's no significant performance gain I'm not likely to merge https://github.com/tomByrer/jquery-focuspoint/commit/d94272df199586016bf8c51615778e05388368b0. There's a real benefit to me in keeping it all on an object in that I can use the console to debug `data` at any point and get a readout of all the vars, nicely grouped together.

**Pull request closed without merging**
