### PR TITLE
[BUGFIX] Enable to focus point behind bullseye by click

### PR DESCRIPTION
**Pull request by l2hm4r**

### CODE REVIEW

**Comment by jonom** [comment]
Thanks but what is this fixing? Is there a browser the helper tool doesn't work in?

**Comment by l2hm4r** [comment]
In Firefox 40.0.x (OS X) it is not possible to click the area in the 
zoom circle. Now it is possible to click directly next the the current 
focus point. Example attached.... now you can click the black point ;)

Regards,
Tim

Am 31.08.15 um 20:13 schrieb Jono Menz:

**Comment by l2hm4r** [comment]
example
Example... :)

**Comment by jonom** [comment]
Thanks for the example, I wasn't able to replicate the problem though. The helper tool in this project works fine for me in Firefox 40.0.3 on Mac without this change, even when clicking right next to the current focus point (within the circle). Maybe it is a problem only with the Typo3 module? Can you confirm?

**Comment by jonom** [comment]
Firefox only appears to have support for the `pointer-events` property enabled by default for non-SVG elements [starting at version 41](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) (and only in nightly builds) so I'm going to close this for now as I can't replicate the problem and it doesn't seem like this property could fix it for most users anyway - but feel free to re-open if you think this does need to be included.

**Comment by l2hm4r** [comment]
Thank you... you are right. It is just a problem of the TYPO3 integration and i fix the issue in a TYPO3 related CSS file. Thank you a lot for the great lib....!! https://github.com/lochmueller/focuspoint/commit/6aca720d5558eee7c565aa9dfd43a9482070c4d2

**Comment by jonom** [comment]
cool :)

**Pull request closed without merging**
